### PR TITLE
Introduce Next Authentication

### PR DESCRIPTION
**Pull request by jskerman**
added Next-Auth deps, created auth route, created provider, google .env vars generated from new auth server hosted on GCP, basic login flow UI and placeholder details page that renders JSON session data.

### CODE REVIEW

**Comment by jskerman** [comment]
@ngd-adams basic auth flow done with examples of how to use it in UI.

**Comment by jskerman** [comment]
Bypassing regular review environment check instead of temp change to callback URL white list because I can't be fucked, have mercy

**Comment by jskerman** [comment]
Bypassing regular review environment check instead of temp change to callback url white list because I can't be fucked, have mercy

**Comment by ngd-adams** [comment]
Legend thanks so much mate. I have a commit waiting but didn't want to merge before asking you. Is it now going to be more difficult?

**Comment by jskerman** [comment]
@ngd-adams depends on if there are conflicts. I'll reveiw it now.

**Pull request merged**
